server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://110.41.137.10:3306/yzhans?useSSL=false
    username: root
    password: cccccc
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo